on: push
name: push CI/CD
jobs:
   continuos-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v2
      - name:
        run: |
         npm install
         npm run build
